services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: tosvng/shopx:nginx
    ports:
      - "80:80"

  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./dashboard
    image: tosvng/shopx:dashboard
    ports:
      - 3000:3000
  client:
    build:
      dockerfile: Dockerfile
      context: ./clients/essence
    image: tosvng/shopx:client
    ports:
      - 4000:4000
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: tosvng/shopx:server
    environment:
      - PORT =3001
      - MONGO_URL=mongodb+srv://shopx:eTGPnERU6je7i4x4@shopx.6vn2rt9.mongodb.net/?retryWrites=true&w=majority
      - PROD_MONGO_URL=mongodb+srv://shopx:eTGPnERU6je7i4x4@shopx.6vn2rt9.mongodb.net/production?retryWrites=true&w=majority
      - JWT_SECRET=f43fea48f54323fe2b441938e3dce96ec018413a093a6bfa0741d53182af1941db3fa9f38d1da9e41c96463f44c22bd3cefca5de68cd7ca65a6228261d339904114483eb163035538010da34fb331b1da2a7518ef7b524c522a8b93cd373d14457e5e9651fa43531ca9d556f69d551bb747ff090bf1ab9b3b993fcd345bee4fe
      - JWT_REFRESH_SECRET=119adf89d8705f7423f50e197a0de99b57cd63f587b9838e4b5190d5019474110167b7a9169c6640b39d5dbd03917c06f93e4d12d8f0072de42beaf1468af5d1bf6d8696ee9784e1f319af6d83679936d8c24e8a1091b933573024659ba2
      - PAYSTACK_KEY=sk_test_555711c3e706e1a78466834f974d4ac6c3ce87a9
      - BUCKET_NAME=shopx-aws-s3-bucket
      - BUCKET_REGION=ca-central-1
      - ACCESS_KEY=AKIASFMWHELIZY2P5JZD
      - SECRET_ACCESS_KEY=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
    ports:
      - 3001:3001
