services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: 149028283089.dkr.ecr.us-east-1.amazonaws.com/shopx:nginx
    ports:
      - "80:80"

  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./dashboard
    image: 149028283089.dkr.ecr.us-east-1.amazonaws.com/shopx:dashboard
    # ports:
    #   - "5000:3000"
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: 149028283089.dkr.ecr.us-east-1.amazonaws.com/shopx:server
    environment:
      - PORT = 3001
      - MONGO_URL = oo
      - PROD_MONGO_URL = pp
      - JWT_SECRET = pp
    # ports:
    #   - "3001:3001"
