services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./dashboard
    # ports:
    #   - "5000:3000"
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - PORT = 3001
      - MONGO_URL = oo
      - PROD_MONGO_URL = pp
      - JWT_SECRET = pp
    # ports:
    #   - "3001:3001"
