services:
  emailservice:
    image: tosvng/shopx:emailservice
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  dashboard:
    image: tosvng/shopx:dashboard
    ports:
      - 3000:3000
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    image: tosvng/shopx:client
    ports:
      - 4000:4000
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  server:
    image: tosvng/shopx:server
    env_file: .env
    ports:
      - 3001:3001
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  analysisServer:
    image: tosvng/shopx:analysisServer
    env_file: .env
    ports:
      - 3002:3002
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  my_network:
    name: my_network
    driver: bridge
