services:
  emailservice:
    build:
      dockerfile: Dockerfile
      context: ./emailServer
    image: tosvng/shopx:emailservice
    ports:
      - 8000:8000
  # nginx:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   image: tosvng/shopx:nginx
  #   ports:
  #     - "80:80"

  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./dashboard
    image: tosvng/shopx:dashboard
    ports:
      - 3000:3000
  client:
    build:
      dockerfile: Dockerfile
      context: ./clients/store
    image: tosvng/shopx:client
    ports:
      - 4000:4000
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: tosvng/shopx:server
    ports:
      - 3001:3001
